import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ToastTemplate from "@/components/templates/toast-template";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        {children}
        <ToastTemplate />
      </body>
    </html>
  );
}
